config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  devise_for :users

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :phone_number, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<section class="bg-dark text-white">
    <div class="container text-center">
       <h1>Contact Us</h1>
     </div>
</section>
<br /><br /><br />

<div class = "container">
    <p class="text-muted mb-0 text-center">
       For any questions or concerns feel free to contact us <br /> 
        ***Contact Form has not been setup*** 
    </p>
    <br />
    
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <form>
  <div class="form-row">
      <div class="col">
  <div class="field">
    <%= f.label :first_name, class: "text-muted mb-0", for: "formGroupExampleInput"%>
  <br>
    <%= f.text_field :first_name, class: "text-muted mb-0", for: "formGroupExampleInput" %>
  </div>
  <div class="field">
    <%= f.label :last_name, class: "text-muted mb-0", for: "formGroupExampleInput" %>
  <br>
    <%= f.text_field :last_name, class: "text-muted mb-0", for: "formGroupExampleInput" %>
  </div>
  <div class="field">
     <label class="text-muted mb-0" for="formGroupExampleInput">
    <%= f.label :email,  class: "text-muted mb-0", for: "formGroupExampleInput" %><br>
    <%= f.text_field :email,  class: "text-muted mb-0", for: "formGroupExampleInput" %>
  </div>
  <div class="field">
    <%= f.label :phone_number,  class: "text-muted mb-0", for: "formGroupExampleInput" %><br>
    <%= f.text_field :phone_number,  class: "text-muted mb-0", for: "formGroupExampleInput" %>
  </div>
  <div class="field">
    <%= f.label :description, class: "text-muted mb-0", for: "formGroupExampleInput" %><br>
    <%= f.text_area :description,  class: "text-muted mb-0", for: "formGroupExampleInput" %>
  </div>
   
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
</form>
</div>
</div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone_number %></td>
        <td><%= contact.description %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<%= render 'form' %>


<!-- link_to 'Back', contacts_path %> -->

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @contact.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @contact.phone_number %>
</p>

<p>
  <strong>Description:</strong>
  <%= @contact.description %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Us To Youth.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
   <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Us To Youth - Building The Next Generation</title>

    <!-- Bootstrap core CSS -->
    <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="/vendor/magnific-popup/magnific-popup.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/creative.min.css" rel="stylesheet">
    <style>
    .container-fluid {
      padding-top: 70px;
      padding-bottom: 70px;
    }
    </style>

</head>
<body>
  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Us To Youth</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <!-- 
            Javascript Links (TODO Later)
            <li class="nav-item">
               link_to 'Our Values', page_path('index#services'), class: "nav-link js-scroll-trigger"
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#portfolio">Our Partners</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
            </li>
            <li class="nav-item">
              <a link_to 'Vendors', page_path('vendors_application'), class: "nav-link" >
            </li>
               <li class="nav-item">
            link_to 'RSVP', page_path('rsvp'), class: "nav-link" 
            </li>
            -->
            <li class="nav-item">
              <%= link_to 'Mission', root_path('/'), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Meet the Team', page_path('team'), class: "nav-link" %>
            </li>
             <li class="nav-item">
              <%= link_to 'About', page_path('about'), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Vendors', page_path('vendors'), class: "nav-link" %>
            </li>
            <li class="nav-item">
               <%= link_to 'Volunteer', page_path('Volunteerform'), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Contact Us', page_path('Contactform'), class: "nav-link" %>
            </li>
            
          </ul>
        </div>
      </div>
    </nav>
<%= yield %>

</body>



  <!-- Bootstrap core JavaScript -->
    <script src="/vendor/jquery/jquery.min.js"></script>
    <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="/vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="/vendor/scrollreveal/scrollreveal.min.js"></script>
    <script src="/vendor/magnific-popup/jquery.magnific-popup.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="/js/creative.min.js"></script>


<!-- Footer -->
<footer class="container-fluid bg-dark text-white text-center">
  <p>	&copy; Us To Youth, Inc. | ustoyouth@gmail.com</p><br>
  <p>Developed by <a href="https://adamtlee.co/">Adam T. Lee</a> | Original Template by <a href ="https://startbootstrap.com/">Startbootstrap</a> | Recommended Browsers: Chrome, Edge, Safari</p> 
</footer>
</html>

app/views/pages/Contactform.html.erb
<section class="bg-dark text-white">
    <div class="container text-center">
       <h1>Contact Us</h1>
     </div>
</section>
<br /><br /><br />
<div class = "container">
    <div class="row">
        <div class="col-lg-12 text-center">
            <h2 class="section-heading">Talk with us.</h2></h2>
                <hr class="my-4">
         </div>
    </div>    
</div>

<div class = "container">
    <div class="col-lg-12 text-center">
         <h5 class="section-heading">
            If you have any questions of concerns please fill out the form below<br />
            Or<br/> 
            Email ustoyouth@gmail.com we will get to you as soon as possible!<br /><br />
            
            Please click the button below to contact us:<br /><br />
             <a class="btn btn-primary btn-xl js-scroll-trigger" href="https://msudenver.qualtrics.com/jfe/form/SV_3KJOewslmcJvvjT" target="_blank">Contact Us</a>
        
         
         </h5>
    </div>
    
</div>
<br />

app/views/pages/about.html.erb
<section class="bg-dark text-white">
    <div class="container text-center">
       <h1>About</h1>
     </div>
</section>
<br /><br /><br />

<div class = "container">
    <div class="row">
        <div class="col-lg-12 text-center">
            <h2 class="section-heading">Who We Are</h2></h2>
                <hr class="my-4">
                <h6 class="section-heading" style = "text-align:left">
                    Us To Youth is a non-profit organization dedicated to bridging the gap between
                    the youth in low-income and at-risk communities. These youth groups range from several
                    activities (sports, arts, etc.) that will serve as a catalyst to healthy lifestyle decisions in
                    the future for the next generation by establishing positive mentors to assist them throughout
                    their childhood. During our first year, we will be working with children in low-income or at-risk
                    communities, and our vendors will be tailored towards physical activities that they can
                    participate in this summer.
                </h6>
         </div>
    </div>    
</div>

<br />

<div class = "container">
    <div class="row">
        <div class="col-lg-12 text-center">
            <h2 class="section-heading">My Personal Story:</h2></h2>
                <hr class="my-4">
                <h6 class="section-heading" style = "text-align:left">
                    I grew up in a rough neighborhood on 13th and Mariposa. Back then, there were these
                    red brick government houses for low-income families. Several of my friends lived in those
                    houses. Parents used to have their kids in the house by 6 pm due to gang violence that would
                    happen at night. My transition from 5th grade to 6th grade was very rough. A lot of my friends
                    started to become active members of local gangs, jumping other kids, and tagging
                    buildings. When they found out that I didn’t want any part of gangs, they started to label me as a
                    target, I’ve been jumped to a point of where I was unconscious, I got into a lot of fights, mostly
                    because I refused to be part of their gangs and tried to defend myself.<br /><br />
                    
                    Later on, I was introduced to Wrestling and Jiu-Jitsu, which paved the path to where I am
                    today. I also found Muay Thai and Boxing much later. These martial arts taught me discipline,
                    gave me confidence, and taught me how to defend myself in real life threatening situations.
                    They’ve also helped me establish positive mentors in my life when I hit rock bottom at times,
                    and have also exposed me to a network of people (Software Engineers,
                    Lawyers, Doctors, etc… all who share a passion for the interests I do) I’ve also received several
                    career opportunities through my connections, One of my favorite occupations is teaching kids
                    Brazilian jiu-jitsu on a weekly basis and being someone they can talk to in situations where they
                    feel down.<br /><br />
                    
                    When I reflect on my past situation, I am thankful for being where I am today. Some of
                    my former friends and classmates that actively participated in gangs in the past are either
                    locked up, disabled or dead due to gang violence, or still stuck in their ways. I don’t think this is
                    entirely their fault; usually in low-income and at-risk communities children have older siblings
                    and mentors who are already actively involved in gangs, and hence by default are pressured
                    into participating in gangs as well. If we could show them alternative paths, it could make a huge
                    impact to a child as it did to me. I’m hoping to do the best I can and pay it forward through my
                    experiences.
                </h6>
         </div>
    </div>    
</div>
<br />
<div class = "container">
    <div class="row">
        <div class="col-lg-12 text-center">
            <h2 class="section-heading">Our Action Plan</h2></h2>
                <hr class="my-4">
                <h6 class="section-heading" style = "text-align:left">
                    We are hosting an event this late spring called “Pledge to Play”. The event will bring
                    children from these communities on to campus. We will coordinate field activities and games to
                    play and introduce them to youth groups within the community to help them stay active and out
                    of trouble for the summer. 
 <br /><br />
                    
                    The kids will participate in an activity called “The Pledge”. They will write a statement that they
                    will stay active and involved in the summer, then dip their hand in their favorite color paint
                    and stamp it on a canvas as a “pledge”. Kids can then take this home and hang it up on their
                    wall as a reminder of what they pledged to do this summer.<br /><br />
                    
                    We are working with Fairview Elementary to bring their 5th grade class onto campus.<br /><br />
                    
                    <b>
                        Event Details: <br />
                        Date: May 16th, 2018 <br/>
                        Address: 890 Auraria Pkwy #310, Denver, CO 80204 <br />
                        Location: P.E Event Center at Auraria Campus <br />
                        Time: 11:00 am to 3:00 pm <br /><br />
                    </b>
                </h6>
         </div>
    </div>    
</div>

app/views/pages/contact.html.erb
<section class="bg-dark text-white">
    <div class="container text-center">
       <h1>Contact Us</h1>
     </div>
</section>
<br /><br /><br />
<div class = "container">
    <p class="text-muted mb-0 text-center">
       For any questions or concerns feel free to contact us <br /> 
        ***Contact Form has not been setup*** <br /> 
        For any questions or comments please email ustoyouth@gmail.com
    </p>
    <br />
    <form>
       <div class="form-row">
            <div class="col">
              <label class="text-muted mb-0" for="formGroupExampleInput">First name:</label>
              <input type="text" class="form-control" placeholder="">
            </div>
            <div class="col">
              <label class="text-muted mb-0" for="formGroupExampleInput">Last name:</label>
              <input type="text" class="form-control" placeholder="">
            </div>
       </div>
            <div class="form-group">
                <label class="text-muted mb-0" for="formGroupExampleInput">Email:</label>
                <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
            </div>
            <div class="form-group">
                <label class="text-muted mb-0" for="formGroupExampleInput">Phone number:</label>
                <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
            </div>
           <div class="form-group">
                <label for="exampleFormControlTextarea1" class="text-muted mb-0">Additional Information:</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
           </div>
      <button class="btn btn-primary">Submit</button>
    </form>
</div>
<br />

app/views/pages/contact1.html.erb
<section class="bg-dark text-white">
    <div class="container text-center">
       <h1>Contact Us</h1>
     </div>
</section>
<br /><br /><br />
<div class = "container">
    <p class="text-muted mb-0 text-center">
       For any questions or concerns feel free to contact us <br /> 
        ***Contact Form has not been setup*** 
    </p>
    <br />
    <form>
       <div class="form-row">
            <div class="col">
              <label class="text-muted mb-0" for="formGroupExampleInput">First name:</label>
              <input type="text" class="form-control" placeholder="">
            </div>
            <div class="col">
              <label class="text-muted mb-0" for="formGroupExampleInput">Last name:</label>
              <input type="text" class="form-control" placeholder="">
            </div>
       </div>
            <div class="form-group">
                <label class="text-muted mb-0" for="formGroupExampleInput">Email:</label>
                <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
            </div>
            <div class="form-group">
                <label class="text-muted mb-0" for="formGroupExampleInput">Phone number:</label>
                <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
            </div>
           <div class="form-group">
                <label for="exampleFormControlTextarea1" class="text-muted mb-0">Additional Information:</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
           </div>
      <button class="btn btn-primary">Submit</button>
    </form>
</div>
<br />

app/views/pages/contact_backup.html.erb
<section class="bg-dark text-white">
    <div class="container text-center">
       <h1>Contact Us</h1>
     </div>
</section>
<br /><br /><br />
<div class = "container">
    <p class="text-muted mb-0 text-center">
       For any questions or concerns feel free to contact us <br /> 
        ***Contact Form has not been setup*** 
    </p>
    <br />
    <form>
       <div class="form-row">
            <div class="col">
              <label class="text-muted mb-0" for="formGroupExampleInput">First name:</label>
              <input type="text" class="form-control" placeholder="">
            </div>
            <div class="col">
              <label class="text-muted mb-0" for="formGroupExampleInput">Last name:</label>
              <input type="text" class="form-control" placeholder="">
            </div>
       </div>
            <div class="form-group">
                <label class="text-muted mb-0" for="formGroupExampleInput">Email:</label>
                <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
            </div>
            <div class="form-group">
                <label class="text-muted mb-0" for="formGroupExampleInput">Phone number:</label>
                <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
            </div>
           <div class="form-group">
                <label for="exampleFormControlTextarea1" class="text-muted mb-0">Additional Information:</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
           </div>
      <button class="btn btn-primary">Submit</button>
    </form>
</div>
<br />

app/views/pages/m.html.erb
<section class="bg-dark text-white">
    <div class="container text-center">
       <h1>Meet The Team</h1>
     </div>
</section>
<br /><br /><br />

    <!-- Page Content -->
    
    <!-- Introduction Row -->
      <div class="container">
        <p class="text-muted mb-0 text-center">
           Helping the next generation. 
        </p>

      <!-- Team Members Row -->
      <div class="row">
        <div class="col-lg-4 col-sm-6 text-center mb-4">
          <img class="rounded-circle img-fluid d-block mx-auto" src="/images/profile-missing-resized.jpg" alt="">
          <h3>Adam</h3>
        </div>
        <div class="col-lg-4 col-sm-6 text-center mb-4">
          <img class="rounded-circle img-fluid d-block mx-auto" src="/images/profile-missing-resized.jpg" alt="">
          <h3>Beatriz<h3/>
        </div>
        <div class="col-lg-4 col-sm-6 text-center mb-4">
          <img class="rounded-circle img-fluid d-block mx-auto" src="/images/profile-missing-resized.jpg" alt="">
          <h3>Lauren</h3>
        </div>
        <div class="col-lg-4 col-sm-6 text-center mb-4">
          <img class="rounded-circle img-fluid d-block mx-auto" src="/images/profile-missing-resized.jpg" alt="">
          <h3>Lacey</h3>
        </div>
        <div class="col-lg-4 col-sm-6 text-center mb-4">
          <img class="rounded-circle img-fluid d-block mx-auto" src="/images/profile-missing-resized.jpg" alt="">
          <h3>Jazz</h3>
        </div>
        <div class="col-lg-4 col-sm-6 text-center mb-4">
          <img class="rounded-circle img-fluid d-block mx-auto" src="/images/profile-missing-resized.jpg" alt="">
          <h3>Mike</h3>
        </div>
      </div>

    </div>
    <!-- /.container -->

<br /><br /><br />

<!--
 <div class="row">
        <div class="col-lg-12">
          <h2 class="my-4">Our Team</h2>
        </div>
        <div class="col-lg-4 col-sm-6 text-center mb-4">
          <img class="rounded-circle img-fluid d-block mx-auto" src="/images/profile-missing-resized.jpg" alt="">
          <h3>Adam
            <small>Job Title</small>
          </h3>
          <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
        </div>
        -->

app/views/pages/rsvp.html.erb
<section class="bg-dark text-white">
    <div class="container text-center">
       <h1>RSVP</h1>
     </div>
</section>
<br /><br /><br />
<div class = "container">
    <p class="text-muted mb-0 text-center">
       We would like to see you at this event! please download the waiver and turn it in to the volunteers
       at the check-in table at the event. Also, please fill out the following fields below to provide us with statistics, 
       and a general idea of how many children we will expect to see (which will assist us in our quantity of snacks we should expect to provide). 
         <br /> 
        ***RSVP Applications have not opened*** 
    </p>
    <br />
    <div class = "form-row">
         <p class="text-muted mb-0 text-center">
             Please download the event waiver form here and submit it to the volunteers at the check-in table at the event: 
         </p>
          <button class="btn btn-info btn-sm">Waiver</button>
     </div>
    <form>
       <div class="form-row">
            <div class="col">
              <label class="text-muted mb-0" for="formGroupExampleInput">First name:</label>
              <input type="text" class="form-control" placeholder="">
            </div>
            <div class="col">
              <label class="text-muted mb-0" for="formGroupExampleInput">Last name:</label>
              <input type="text" class="form-control" placeholder="">
            </div>
       </div>
            <div class="form-group">
                <label class="text-muted mb-0" for="formGroupExampleInput">Email:</label>
                <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
            </div>
            <div class="form-group">
                <label class="text-muted mb-0" for="formGroupExampleInput">Phone number:</label>
                <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
            </div>
            <div class="form-group">
                <label class="text-muted mb-0" for="formGroupExampleInput">T-shirt size:</label>
                <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
            </div>
            <div class="form-group">
                <label class="text-muted mb-0" for="formGroupExampleInput">How did you hear about us?:</label>
                <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
            </div>
            <div class="form-group">
                <label class="text-muted mb-0" for="formGroupExampleInput">How many children will you bring?:</label>
                <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
            </div>
            <div class="text-muted mb-0">
                <label class="form-check-label">
                <input type="checkbox" class="form-check-input">
                  I will submit the waiver in person at the event 
                </label>
             </div><br />
            <div class="form-group">
                <label for="exampleFormControlTextarea1" class="text-muted mb-0">Additional Information:</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
           </div>
      <button class="btn btn-primary">Submit</button>
    </form>
</div>
<br />

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>